<?php
defined('BASEPATH') || exit('No direct script access allowed');

require_once APPPATH.'/controllers/api/frontend/v1/issues/IssueChecker.php';

class PersonalIssueChecker extends IssueChecker
{
	const DEFAULT_PERMISSION = 'basis/mitarbeiter:r';
	const RESTRICTED_PERMISSION = 'extension/pv21_handyverwaltung:r';
	const SCHLUESSELVERWALTUNG_PERMISSION = 'extension/pv21_schluesselver:r';
	const KONTAKTDATENVERWALTUNG_PERMISSION = 'extension/pv21_kontaktdatenver:r';

	public function __construct()
	{
		parent::__construct(
			array(
				'checkPerson' => self::DEFAULT_PERMISSION,
				'countPersonOpenIssues' => [
					self::DEFAULT_PERMISSION,
					self::RESTRICTED_PERMISSION,
					self::SCHLUESSELVERWALTUNG_PERMISSION,
					self::KONTAKTDATENVERWALTUNG_PERMISSION
				]
			)
		);

		//$this->_app = 'personalverwaltung';
		$this->_extensionName = 'FHC-Core-Personalverwaltung';

		// set fehler codes which can be resolved by the job
		// structure: fehlercode => class (library) name for resolving
		$this->_codeLibMappings = array(
			'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0001' => 'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0001',
			'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0002' => 'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0002',
			'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0003' => 'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0003',
			'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0004' => 'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0004',
			'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0005' => 'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0005',
			'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0001' => 'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0001',
			'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0002' => 'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0002',
			'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0003' => 'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0003',
			'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0004' => 'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0004',
			'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0005' => 'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0005',
			'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0006' => 'PERSONALVERWALTUNG_VERTRAGSBESTANDTEIL_0006',
			'PERSONALVERWALTUNG_GEHALT_0001' => 'PERSONALVERWALTUNG_GEHALT_0001',
			'PERSONALVERWALTUNG_GEHALT_0002' => 'PERSONALVERWALTUNG_GEHALT_0002',
			'PERSONALVERWALTUNG_GEHALT_0003' => 'PERSONALVERWALTUNG_GEHALT_0003',
			'PERSONALVERWALTUNG_GEHALT_0004' => 'PERSONALVERWALTUNG_GEHALT_0004',
			'PERSONALVERWALTUNG_FUNKTION_0001' => 'PERSONALVERWALTUNG_FUNKTION_0001',
			'PERSONALVERWALTUNG_FUNKTION_0002' => 'PERSONALVERWALTUNG_FUNKTION_0002'
		);

		// fehler which are resolved by the job the same way as they are produced
		// structure: fehlercode => class (library) name for resolving in "plausichecks" folder
		$this->_codeProducerLibMappings = array(
			'PERSONALVERWALTUNG_GEHALT_0005' => 'ValorisierungsBetragAbweichendVonBerechnung',
			'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0006' => 'EchteDienstverhaeltnisseOhneOeVertragsbestandteil',
			'PERSONALVERWALTUNG_DIENSTVERHAELTNIS_0007' => 'EchteDienstverhaeltnisseOhneKostenstelleVertragsbestandteil'
		);
	}
}
